#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the organizingContainers function below.
def organizingContainers(container):
    m1=[]
    m2=[]
    for i in range(len(container)):
        
        sum2=0
        sum1=sum(container[i])
        for j in range(len(container)):
           sum2+=container[j][i]

        m1.append(sum1)
        m2.append(sum2)

    for i in range(len(m1)):
        if m1[i] in m2:
            m2.remove(m1[i]) 
    print(m2)
    return "Possible" if m2 == [] else "Impossible"

        #if sum1!=sum2:
                #return "Impossible"
            


        
    #return "Possible"
            

   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        n = int(input())

        container = []

        for _ in range(n):
            container.append(list(map(int, input().rstrip().split())))

        result = organizingContainers(container)

        fptr.write(result + '\n')

    fptr.close()
